"""다시 원래대로

Revision ID: 0457bdb8ef0e
Revises: ae2794ee91f5
Create Date: 2024-08-25 21:01:51.554021

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0457bdb8ef0e'
down_revision = 'ae2794ee91f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fcuser', schema=None) as batch_op:
        batch_op.add_column(sa.Column('matched_team_id', sa.Integer(), nullable=True))
        batch_op.drop_column('room')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fcuser', schema=None) as batch_op:
        batch_op.add_column(sa.Column('room', mysql.VARCHAR(length=50), nullable=True))
        batch_op.drop_column('matched_team_id')

    # ### end Alembic commands ###
