"""add chat_message table

Revision ID: 169780d77807
Revises: 04e525f487f9
Create Date: 2024-08-25 19:29:52.842435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '169780d77807'
down_revision = '04e525f487f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_message',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user', sa.String(length=50), nullable=True),
    sa.Column('room', sa.String(length=50), nullable=False),
    sa.Column('message', sa.String(length=200), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat_message')
    # ### end Alembic commands ###
