"""Add matched_team_id and matched_team_users

Revision ID: 387c91f9062b
Revises: 367f9cb8eea7
Create Date: 2024-08-21 17:02:06.012918

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '387c91f9062b'
down_revision = '367f9cb8eea7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fcuser', schema=None) as batch_op:
        batch_op.add_column(sa.Column('matched_team_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'team', ['matched_team_id'], ['id'])
        batch_op.drop_column('socket_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fcuser', schema=None) as batch_op:
        batch_op.add_column(sa.Column('socket_id', mysql.VARCHAR(length=120), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('matched_team_id')

    # ### end Alembic commands ###
