"""Add unique_number to Fcuser

Revision ID: 61779e8f45ec
Revises: f5713f2035cc
Create Date: 2024-07-31 01:01:27.824314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61779e8f45ec'
down_revision = 'f5713f2035cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fcuser', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unique_number', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint(None, ['unique_number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fcuser', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('unique_number')

    # ### end Alembic commands ###
