"""Add room and remove matched_team_id

Revision ID: 6eef20a0de46
Revises: 0457bdb8ef0e
Create Date: 2024-08-25 21:07:15.888714

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6eef20a0de46'
down_revision = '0457bdb8ef0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fcuser', schema=None) as batch_op:
        batch_op.add_column(sa.Column('room', sa.String(length=50), nullable=True))
        batch_op.drop_column('matched_team_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fcuser', schema=None) as batch_op:
        batch_op.add_column(sa.Column('matched_team_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('room')

    # ### end Alembic commands ###
