"""Add end column

Revision ID: 88faf0d4de9d
Revises: ac51e548b96b
Create Date: 2024-08-26 13:40:41.078361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88faf0d4de9d'
down_revision = 'ac51e548b96b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fcuser', schema=None) as batch_op:
        batch_op.add_column(sa.Column('end', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fcuser', schema=None) as batch_op:
        batch_op.drop_column('end')

    # ### end Alembic commands ###
