"""Remove matched_team_id and add room to Fcuser

Revision ID: ae2794ee91f5
Revises: c8b25496a984
Create Date: 2024-08-25 20:58:05.455965

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ae2794ee91f5'
down_revision = 'c8b25496a984'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fcuser', schema=None) as batch_op:
        batch_op.add_column(sa.Column('room', sa.String(length=50), nullable=True))
        batch_op.drop_column('matched_team_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fcuser', schema=None) as batch_op:
        batch_op.add_column(sa.Column('matched_team_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('room')

    # ### end Alembic commands ###
