"""Add matched_team_id and update relationships

Revision ID: b8e77db6a95c
Revises: 387c91f9062b
Create Date: 2024-08-21 17:06:12.057806

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b8e77db6a95c'
down_revision = '387c91f9062b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fcuser', schema=None) as batch_op:
        batch_op.drop_constraint('fcuser_ibfk_2', type_='foreignkey')

    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=80), nullable=False))
        batch_op.drop_constraint('team_ibfk_1', type_='foreignkey')
        batch_op.drop_column('team_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.add_column(sa.Column('team_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('team_ibfk_1', 'team', ['team_id'], ['id'])
        batch_op.drop_column('name')

    with op.batch_alter_table('fcuser', schema=None) as batch_op:
        batch_op.create_foreign_key('fcuser_ibfk_2', 'team', ['matched_team_id'], ['id'])

    # ### end Alembic commands ###
