"""원래대로

Revision ID: c8b25496a984
Revises: fb2c88d18668
Create Date: 2024-08-25 20:47:54.027813

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c8b25496a984'
down_revision = 'fb2c88d18668'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fcuser', schema=None) as batch_op:
        batch_op.add_column(sa.Column('matched_team_id', sa.Integer(), nullable=True))
        batch_op.drop_column('room')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fcuser', schema=None) as batch_op:
        batch_op.add_column(sa.Column('room', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('matched_team_id')

    # ### end Alembic commands ###
