"""Add gender field to Fcuser

Revision ID: f5713f2035cc
Revises: a6a5850286bf
Create Date: 2024-07-28 04:11:45.519039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5713f2035cc'
down_revision = 'a6a5850286bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fcuser', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.String(length=10), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fcuser', schema=None) as batch_op:
        batch_op.drop_column('gender')

    # ### end Alembic commands ###
