"""Rename matched_team_id to room and update values

Revision ID: fb2c88d18668
Revises: ecaa305b9ef8
Create Date: 2024-08-25 20:39:25.595775

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fb2c88d18668'
down_revision = 'ecaa305b9ef8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_message', schema=None) as batch_op:
        batch_op.alter_column('room',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)

    with op.batch_alter_table('fcuser', schema=None) as batch_op:
        batch_op.add_column(sa.Column('room', sa.Integer(), nullable=True))
        batch_op.drop_column('matched_team_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fcuser', schema=None) as batch_op:
        batch_op.add_column(sa.Column('matched_team_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('room')

    with op.batch_alter_table('chat_message', schema=None) as batch_op:
        batch_op.alter_column('room',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###
